(executables
 (names
  test_static_person
  test_static_pet
  test_versioned_bookmark
  test_postgres_static_person
  test_postgres_static_pet
  test_postgres_versioned_bookmark)
 (modules
  (:standard \ "test_utils"))
 (libraries
  test_utils
  petrol
  caqti
  caqti-lwt.unix
  caqti-driver-sqlite3
  caqti-driver-postgresql))

(library
 (name test_utils)
 (modules "test_utils")
 (libraries
  petrol
  caqti
  caqti-lwt.unix
  caqti-driver-sqlite3
  caqti-driver-postgresql))
